services:
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: recordsjs
    ports:
      - 3306:3306
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entry-point-initdb.d/
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recordsjs
    ports:
      - 5432:5432
    volumes:
      - ./docker-entrypoint-initdb.d/datajs.sql:/master/data/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
